export const questions = [
    {
        id: 1,
        question: 'Hôm nay bạn thế nào????',
        a: 'hmm',
        b: 'Uhm',
        c: 'Tốt',
        d: 'Nấu ăn',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 2,
        question: 'Thủ đô của Pháp là gì?',
        a: 'London',
        b: 'Paris',
        c: 'Berlin',
        d: 'Madrid',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 3,
        question: 'Hành tinh nào được gọi là hành tinh Đỏ?',
        a: 'Trái Đất',
        b: 'Sao Hỏa',
        c: 'Sao Kim',
        d: 'Sao Mộc',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 2,
        status: true
    },
    {
        id: 4,
        question: '2 + 2 bằng bao nhiêu?',
        a: '3',
        b: '4',
        c: '5',
        d: '22',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 3,
        status: true
    },
    {
        id: 5,
        question: 'Khi trộn màu đỏ và xanh dương, ta được màu gì?',
        a: 'Tím',
        b: 'Cam',
        c: 'Xanh lá',
        d: 'Hồng',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 5,
        status: true
    },
    {
        id: 6,
        question: 'Động vật có vú lớn nhất là gì?',
        a: 'Voi',
        b: 'Cá voi xanh',
        c: 'Hươu cao cổ',
        d: 'Tê giác',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 2,
        status: true
    },
    {
        id: 7,
        question: 'Ai Cập nằm ở châu lục nào?',
        a: 'Châu Phi',
        b: 'Châu Á',
        c: 'Châu Âu',
        d: 'Châu Úc',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 4,
        status: true
    },
    {
        id: 8,
        question: 'Nhiệt độ sôi của nước là bao nhiêu?',
        a: '90°C',
        b: '100°C',
        c: '120°C',
        d: '80°C',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 6,
        status: true
    },
    {
        id: 9,
        question: 'Loài vật nào được gọi là chúa tể sơn lâm?',
        a: 'Hổ',
        b: 'Voi',
        c: 'Sư tử',
        d: 'Gấu',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 7,
        status: true
    },
    {
        id: 10,
        question: 'Cây sử dụng khí nào để quang hợp?',
        a: 'Oxy',
        b: 'Hydro',
        c: 'Carbon Dioxide (CO₂)',
        d: 'Nitơ',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 8,
        status: true
    },
    {
        id: 11,
        question: 'Hình gì có ba cạnh?',
        a: 'Hình tròn',
        b: 'Hình tam giác',
        c: 'Hình vuông',
        d: 'Hình chữ nhật',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 9,
        status: true
    },
    {
        id: 12,
        question: 'Mùa nào đến sau mùa hè?',
        a: 'Mùa đông',
        b: 'Mùa thu',
        c: 'Mùa xuân',
        d: 'Mùa mưa',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 10,
        status: true
    },
    {
        id: 13,
        question: 'Bầu trời có màu gì vào một ngày quang đãng?',
        a: 'Xanh dương',
        b: 'Đỏ',
        c: 'Xanh lá',
        d: 'Vàng',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 11,
        status: true
    },
    {
        id: 14,
        question: 'Chúng ta dùng giác quan nào để ngửi?',
        a: 'Thị giác',
        b: 'Xúc giác',
        c: 'Thính giác',
        d: 'Khứu giác',
        correctAns: 'd',
        userAns: null,
        isCorrect: null,
        level: 12,
        status: true
    },
    {
        id: 15,
        question: 'Con nhện có bao nhiêu chân?',
        a: '6',
        b: '8',
        c: '10',
        d: '12',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 13,
        status: true
    },
    {
        id: 16,
        question: 'Ong tạo ra gì?',
        a: 'Sữa',
        b: 'Sáp',
        c: 'Mật ong',
        d: 'Dầu',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 14,
        status: true
    },
    {
        id: 17,
        question: 'Một năm nhuận có bao nhiêu ngày?',
        a: '364',
        b: '365',
        c: '366',
        d: '360',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 15,
        status: true
    },
    {
        id: 18,
        question: 'Con chó con gọi là gì?',
        a: 'Con gấu con',
        b: 'Mèo con',
        c: 'Chó con',
        d: 'Gà con',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 14,
        status: true
    },
    {
        id: 19,
        question: 'Đại dương nào lớn nhất thế giới?',
        a: 'Đại Tây Dương',
        b: 'Ấn Độ Dương',
        c: 'Bắc Băng Dương',
        d: 'Thái Bình Dương',
        correctAns: 'd',
        userAns: null,
        isCorrect: null,
        level: 15,
        status: true
    },
    {
        id: 20,
        question: 'H2O thường được gọi là gì?',
        a: 'Muối',
        b: 'Nước',
        c: 'Hydro',
        d: 'Oxy',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 15,
        status: true
    }
];

export const prizeMap = {
    1: 200,
    2: 300,
    3: 500,
    4: 1000,
    5: 2000,
    6: 5000,
    7: 10000,
    8: 15000,
    9: 25000,
    10: 50000,
    11: 75000,
    12: 100000,
    13: 150000,
    14: 250000,
    15: 500000
};